apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
{{- if eq .Values.service.type "NodePort" }}
  {{- if eq .Values.tls "external" }}
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.ports.nodePort }}
      name: http-80
  {{- else }}
    - port: 443
      targetPort: 443
      protocol: TCP
      nodePort: {{ .Values.service.ports.nodePort }}
      name: https-443
  {{- end }}
{{- else }}
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
{{- end }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "rancher.fullname" . }}
