on: 
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, edited, deleted]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: kingsd041/git-sync@ksd/v2.0
      env:
        SOURCE_REPO: "kingsd041/pandaria"
        SOURCE_BRANCH: "refs/remotes/source/release/v2.2-ent"
        DESTINATION_REPO: "kingsd041/pandaria-vip"
        DESTINATION_BRANCH: "refs/heads/release/v2.2-ent"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
